version: "3.8"

services:
  half-life:
    image: ghcr.io/youruser/half-life:latest
    container_name: half-life
    user: "${PGID:-1000}:${PUID:-1000}"
    networks:
      - hl_net
    restart: unless-stopped
    ports:
      - "${HLSERVER_PORT:-27015}:${HLSERVER_PORT:-27015}/udp"
    environment:
      HLSERVER_PORT: "${HLSERVER_PORT:-27015}"
      HLSERVER_MAP: "${HLSERVER_MAP:-stalkyard}"
      HLSERVER_MAXPLAYERS: "${HLSERVER_MAXPLAYERS:-16}"
      HLSERVER_BOTS: "${HLSERVER_BOTS:-true}"
      HLSERVER_BOTS_COUNT: "${HLSERVER_BOTS_COUNT:-10}"
    volumes:
      - ./valve:/data/valve
      - ./logs:/data/logs

networks:
  hl_net:
    external: true
