#!/usr/bin/env bash
set -e

# =============================================================================
# Server settings
# =============================================================================
: "${HLSERVER_PORT:=27015}"
: "${HLSERVER_IP:=0.0.0.0}"
: "${HLSERVER_MAP:=stalkyard}"
: "${HLSERVER_MAXPLAYERS:=16}"
: "${HLSERVER_FRAGLIMIT:=0}"
: "${HLSERVER_TIMELIMIT:=0}"
: "${HLSERVER_MAPCYCLE:=}"
: "${HLSERVER_GAME:=valve}"
: "${HLSERVER_TICRATE:=10}"

# =============================================================================
# Bot settings (bot10 / HPB bot cvars only)
# =============================================================================
: "${HLSERVER_BOTS:=false}"           # Enable bots
: "${HLSERVER_BOTS_COUNT:=5}"         # Number of bots to add
: "${HLSERVER_BOT_SKILL:=1}"          # Default skill 1-5 (1=easiest, 5=hardest)
: "${HLSERVER_BOT_STOP:=0}"           # 1 = freeze all bots
: "${HLSERVER_BOT_CHAT:=0}"           # 1 = enable bot chat
: "${HLSERVER_BOT_NAMES:=}"           # Comma-separated bot names (optional)

# Weapon permissions (1=allow, 0=deny)
: "${HLSERVER_BOT_ALLOW_ROGUES:=1}"
: "${HLSERVER_BOT_ALLOW_PISTOLS:=1}"
: "${HLSERVER_BOT_ALLOW_SHOTGUNS:=1}"
: "${HLSERVER_BOT_ALLOW_MG:=1}"
: "${HLSERVER_BOT_ALLOW_SMG:=1}"
: "${HLSERVER_BOT_ALLOW_RIFLES:=1}"
: "${HLSERVER_BOT_ALLOW_GRENADES:=1}"
: "${HLSERVER_BOT_ALLOW_RPG:=1}"
: "${HLSERVER_BOT_ALLOW_GAUSS:=1}"
: "${HLSERVER_BOT_ALLOW_EGON:=1}"
: "${HLSERVER_BOT_ALLOW_SATCHEL:=1}"
: "${HLSERVER_BOT_ALLOW_TRIPMINE:=1}"
: "${HLSERVER_BOT_ALLOW_SNARKS:=1}"
: "${HLSERVER_BOT_ALLOW_HORNETGUN:=1}"

# =============================================================================
# Paths
# =============================================================================
: "${XASH3D_BASE:=/opt/xash}"
: "${HLSDK_LIBS_PATH:=/opt/hlsdk-libs}"

game_path="/data/${HLSERVER_GAME}"
xash_bin="${XASH3D_BASE}/xash"

# =============================================================================
# Sanity checks
# =============================================================================
if [ ! -d "$game_path" ]; then
  echo "❌ Game directory not found: $game_path" >&2
  exit 1
fi

# Determine architecture suffix
arch=$(uname -m)
case "$arch" in
  x86_64)  suffix=amd64 ;;
  aarch64) suffix=arm64 ;;
  *)       suffix=$arch ;;
esac

# Select the appropriate DLL
if [[ "$HLSERVER_BOTS" == "true" ]]; then
  dll_name="hl_bot_${suffix}.so"
else
  dll_name="hl_master_${suffix}.so"
fi

dll_path="${HLSDK_LIBS_PATH}/${dll_name}"
if [ ! -f "$dll_path" ]; then
  echo "❌ DLL not found: $dll_path" >&2
  exit 1
fi

# =============================================================================
# Generate bot.cfg — addbot commands ONLY
# The bot10 DLL reads this file itself after initialization.
# Do NOT put cvars here; they must come from the CLI (see cmd[] below).
# =============================================================================
if [[ "$HLSERVER_BOTS" == "true" ]]; then
  bot_cfg="$game_path/bot.cfg"
  echo "🤖 Generating bot.cfg: $bot_cfg ($HLSERVER_BOTS_COUNT bots)"
  {
    echo "// Auto-generated by entrypoint — addbot commands only"
    if [[ -n "$HLSERVER_BOT_NAMES" ]]; then
      IFS=',' read -ra names <<< "$HLSERVER_BOT_NAMES"
      # Add named bots first, then fill the rest unnamed
      named_count=${#names[@]}
      for name in "${names[@]}"; do
        echo "addbot \"${name}\""
      done
      remaining=$(( HLSERVER_BOTS_COUNT - named_count ))
      for i in $(seq 1 "$remaining"); do
        [[ $i -gt 0 ]] && echo "addbot"
      done
    else
      for i in $(seq 1 "$HLSERVER_BOTS_COUNT"); do
        echo "addbot"
      done
    fi
  } > "$bot_cfg"
fi

# =============================================================================
# Generate mapcycle.txt
# =============================================================================
if [[ -n "$HLSERVER_MAPCYCLE" ]]; then
  echo "📄 Generating mapcycle.txt"
  echo "$HLSERVER_MAPCYCLE" | tr ',' '\n' > "$game_path/mapcycle.txt"
fi

# =============================================================================
# Generate server.cfg
# =============================================================================
server_cfg="$game_path/server.cfg"
echo "📄 Generating server.cfg"
{
  echo "// Auto-generated by entrypoint"
  echo "mp_fraglimit $HLSERVER_FRAGLIMIT"
  echo "mp_timelimit $HLSERVER_TIMELIMIT"
  echo "deathmatch 1"
  echo "mp_chattime 5"
} > "$server_cfg"

# =============================================================================
# Generate autoexec.cfg
# =============================================================================
autoexec_cfg="$game_path/autoexec.cfg"
echo "📄 Generating autoexec.cfg"
{
  echo "// Auto-generated by entrypoint"
} > "$autoexec_cfg"

# =============================================================================
# Build xash3d command
# Bot10 cvars are passed as + args — the engine queues them and executes
# them after the game DLL is fully initialized, avoiding "Unknown command"
# warnings that occur when cvars are read from config files too early.
# =============================================================================
declare -a cmd
cmd=(
  -dll "$dll_path"
  -ip "$HLSERVER_IP"
  -port "$HLSERVER_PORT"
  +map "$HLSERVER_MAP"
  +maxplayers "$HLSERVER_MAXPLAYERS"
  +sys_ticrate "$HLSERVER_TICRATE"
  +developer 0
  +fps_override 0
)

# Append bot cvars only when bots are enabled
if [[ "$HLSERVER_BOTS" == "true" ]]; then
  cmd+=(
    +bot_skill              "$HLSERVER_BOT_SKILL"
    +bot_stop               "$HLSERVER_BOT_STOP"
    +bot_chat               "$HLSERVER_BOT_CHAT"
    +bot_allow_rogues       "$HLSERVER_BOT_ALLOW_ROGUES"
    +bot_allow_pistols      "$HLSERVER_BOT_ALLOW_PISTOLS"
    +bot_allow_shotguns     "$HLSERVER_BOT_ALLOW_SHOTGUNS"
    +bot_allow_mg           "$HLSERVER_BOT_ALLOW_MG"
    +bot_allow_smg          "$HLSERVER_BOT_ALLOW_SMG"
    +bot_allow_rifles       "$HLSERVER_BOT_ALLOW_RIFLES"
    +bot_allow_grenades     "$HLSERVER_BOT_ALLOW_GRENADES"
    +bot_allow_rpg          "$HLSERVER_BOT_ALLOW_RPG"
    +bot_allow_gauss        "$HLSERVER_BOT_ALLOW_GAUSS"
    +bot_allow_egon         "$HLSERVER_BOT_ALLOW_EGON"
    +bot_allow_satchel      "$HLSERVER_BOT_ALLOW_SATCHEL"
    +bot_allow_tripmine     "$HLSERVER_BOT_ALLOW_TRIPMINE"
    +bot_allow_snarks       "$HLSERVER_BOT_ALLOW_SNARKS"
    +bot_allow_hornetgun    "$HLSERVER_BOT_ALLOW_HORNETGUN"
  )
fi

# =============================================================================
# Launch
# =============================================================================
echo "🚀 Launching: $xash_bin -game $HLSERVER_GAME ${cmd[*]}"
cd /data
exec "$xash_bin" -game "$HLSERVER_GAME" "${cmd[@]}"
