#!/usr/bin/env bash
set -e

# =============================================================================
# Server settings
# =============================================================================
: "${HLSERVER_PORT:=27015}"
: "${HLSERVER_IP:=0.0.0.0}"
: "${HLSERVER_MAP:=stalkyard}"
: "${HLSERVER_MAXPLAYERS:=16}"
: "${HLSERVER_FRAGLIMIT:=0}"
: "${HLSERVER_TIMELIMIT:=0}"
: "${HLSERVER_MAPCYCLE:=}"
: "${HLSERVER_GAME:=valve}"
: "${HLSERVER_TICRATE:=10}"
: "${HLSERVER_NAME:=Half-Life Server}"

# =============================================================================
# Bot settings
#
# The bot10 DLL (botman's HPB Bot) has NO runtime cvars.
# All bot control is via bot.cfg, parsed by the DLL itself in StartFrame().
#
# bot.cfg supported commands:
#   botskill N          — default skill for bots with no explicit skill (1–5)
#   botdontshoot N      — 0=bots shoot, 1=bots don't shoot
#   min_bots N          — kick a bot when a human joins (floor)
#   max_bots N          — auto-fill server up to this count
#   addbot [skin] [name] [skill]  — spawn one bot
#   pause N             — wait N seconds (required between addbot calls)
#
# Skill scale: 1=best (hardest to beat), 5=worst (easiest to beat)
#
# Valid skins: barney gina gman gordon helmet hgrunt recon robo scientist zombie
# =============================================================================
: "${HLSERVER_BOTS:=false}"
: "${HLSERVER_BOTS_COUNT:=5}"
: "${HLSERVER_BOT_SKILL:=3}"        # 1=best  5=worst  (default in source is 3)
: "${HLSERVER_BOT_DONTSHOOT:=0}"    # 0=bots shoot  1=bots don't shoot
: "${HLSERVER_BOT_MIN:=0}"          # min bots to keep when humans join
: "${HLSERVER_BOT_MAX:=0}"          # auto-fill up to this count (0=disabled)
: "${HLSERVER_BOT_NAMES:=}"         # optional comma-separated: "skin:name,skin:name"
                                    # e.g. "gordon:Freeman,barney:Calhoun"
                                    # skin-only:  "gordon,barney"
                                    # name-only:  ":Freeman,:Calhoun"

# =============================================================================
# Paths
# =============================================================================
: "${XASH3D_BASE:=/opt/xash}"
: "${HLSDK_LIBS_PATH:=/opt/hlsdk-libs}"

game_path="/data/${HLSERVER_GAME}"
xash_bin="${XASH3D_BASE}/xash"

# =============================================================================
# Sanity checks
# =============================================================================
if [ ! -d "$game_path" ]; then
  echo "❌ Game directory not found: $game_path" >&2
  exit 1
fi

arch=$(uname -m)
case "$arch" in
  x86_64)  suffix=amd64 ;;
  aarch64) suffix=arm64 ;;
  *)       suffix=$arch ;;
esac

if [[ "$HLSERVER_BOTS" == "true" ]]; then
  dll_name="hl_bot_${suffix}.so"
else
  dll_name="hl_master_${suffix}.so"
fi

dll_path="${HLSDK_LIBS_PATH}/${dll_name}"
if [ ! -f "$dll_path" ]; then
  echo "❌ DLL not found: $dll_path" >&2
  exit 1
fi

# =============================================================================
# Generate bot.cfg
#
# This file is parsed by the bot DLL itself inside StartFrame() — NOT by the
# engine. Commands are executed in order. A 1-second pause between addbot
# calls is mandatory or the engine crashes.
#
# addbot syntax: addbot [skin] [name] [skill]
#   - skin:  one of the 10 valid model names, or empty for random
#   - name:  display name, or empty to use the skin's default name
#   - skill: 1–5 (1=best, 5=worst), or empty to use botskill default
#
# HLSERVER_BOT_NAMES format: "skin:name" pairs, comma-separated.
#   Examples:
#     "gordon:Freeman,barney:Calhoun"   — named bots with specific skins
#     "gordon,barney,zombie"            — specific skins, default names
#     ":Freeman,:Calhoun"               — random skins, custom names
#     ""                                — all random skins and names
# =============================================================================
if [[ "$HLSERVER_BOTS" == "true" ]]; then
  bot_cfg="${game_path}/bot.cfg"
  echo "🤖 Generating bot.cfg: $bot_cfg ($HLSERVER_BOTS_COUNT bots, skill=$HLSERVER_BOT_SKILL)"
  {
    echo "# Auto-generated by entrypoint"
    echo "# botman's HPB Bot #10 — skill: 1=best  5=worst"
    echo "botskill ${HLSERVER_BOT_SKILL}"
    echo "# botdontshoot: 0=shoot  1=do not shoot"
    echo "botdontshoot ${HLSERVER_BOT_DONTSHOOT}"

    if [[ "$HLSERVER_BOT_MIN" -gt 0 ]]; then
      echo "min_bots ${HLSERVER_BOT_MIN}"
    fi

    if [[ "$HLSERVER_BOT_MAX" -gt 0 ]]; then
      echo "max_bots ${HLSERVER_BOT_MAX}"
    fi

    echo "# addbot [skin] [name] [skill] — pause 1 required between each"

    count=0

    if [[ -n "$HLSERVER_BOT_NAMES" ]]; then
      IFS=',' read -ra entries <<< "$HLSERVER_BOT_NAMES"
      for entry in "${entries[@]}"; do
        [[ $count -ge $HLSERVER_BOTS_COUNT ]] && break
        entry=$(echo "$entry" | xargs)  # trim whitespace
        skin="${entry%%:*}"
        name="${entry##*:}"
        # If no colon was present, entry==skin and name==skin (same string)
        [[ "$entry" != *":"* ]] && name=""
        echo "addbot ${skin} ${name} ${HLSERVER_BOT_SKILL}"
        echo "pause 1"
        count=$(( count + 1 ))
      done
    fi

    # Fill remaining slots with random skin/name at the configured skill
    while [[ $count -lt $HLSERVER_BOTS_COUNT ]]; do
      echo "addbot  "
      echo "pause 1"
      count=$(( count + 1 ))
    done

  } > "$bot_cfg"
fi

# =============================================================================
# Generate mapcycle.txt
# =============================================================================
if [[ -n "$HLSERVER_MAPCYCLE" ]]; then
  echo "📄 Generating mapcycle.txt"
  echo "$HLSERVER_MAPCYCLE" | tr ',' '\n' > "${game_path}/mapcycle.txt"
fi

# =============================================================================
# Generate server.cfg
# =============================================================================
echo "📄 Generating server.cfg"
cat > "${game_path}/server.cfg" << EOF
// Auto-generated by entrypoint
hostname "$HLSERVER_NAME"
mp_fraglimit $HLSERVER_FRAGLIMIT
mp_timelimit $HLSERVER_TIMELIMIT
deathmatch 1
mp_chattime 5
EOF

# =============================================================================
# Generate autoexec.cfg
# =============================================================================
echo "📄 Generating autoexec.cfg"
cat > "${game_path}/autoexec.cfg" << EOF
// Auto-generated by entrypoint
EOF

# =============================================================================
# Build xash3d command
# No +bot_* args — the bot DLL has zero registered cvars.
# All bot control is via bot.cfg which the DLL reads itself.
# =============================================================================
declare -a cmd
cmd=(
  -dll    "$dll_path"
  -ip     "$HLSERVER_IP"
  -port   "$HLSERVER_PORT"
  +map    "$HLSERVER_MAP"
  +maxplayers "$HLSERVER_MAXPLAYERS"
  +sys_ticrate "$HLSERVER_TICRATE"
  +developer 0
  +fps_override 0
)

echo "🚀 Launching: $xash_bin -game $HLSERVER_GAME ${cmd[*]}"
cd /data
exec "$xash_bin" -game "$HLSERVER_GAME" "${cmd[@]}"
